	return MUI_NewObject(MUIC_Application,
		MUIA_Application_Title, (ULONG)"A MUI WINDOW",
		MUIA_Application_Version, (ULONG)"0.1",
		MUIA_Application_Window, (Win = MUI_NewObject(MUIC_Window,
			MUIA_Window_Title, (ULONG)"My window..",
			MUIA_Window_ID, (ULONG)"winny",
			MUIA_Window_Activate, TRUE,
			MUIA_Window_Height, 100,
			MUIA_Window_Width, 100,
			MUIA_Window_CloseGadget, TRUE,
			MUIA_Window_RootObject, MUI_NewObject(MUIC_Group,
				MUIA_Group_Child, MUI_NewObject(MUIC_Text,
					MUIA_Text_Contents, (ULONG)"Hello world!",
				TAG_END),
				MUIA_Group_Child, (InKnob = MUI_NewObject(MUIC_Knob,
					MUIA_Width, 100L,
					MUIA_Height, 100L,
					MUIA_Numeric_Min, 0L,
					MUIA_Numeric_Max, 100L,	
				TAG_END)),
				MUIA_Group_Child, (OutText = MUI_NewObject(MUIC_String,
					MUIA_String_Contents, (ULONG)"Another one!",
				TAG_END)),
			TAG_END),
		TAG_END)),
	TAG_END);
	
	
					MUIA_Group_Child, (OutText = MUI_MakeObject(MUIO_Button,
					"QUIT",
				TAG_END)),
	
		return MUI_NewObject(MUIC_Application,
		MUIA_Application_Title, (ULONG)"A MUI WINDOW",
		MUIA_Application_Version, (ULONG)"0.1",
		MUIA_Application_Window, (Win = MUI_NewObject(MUIC_Window,
			MUIA_Window_Title, (ULONG)"My window..",
			MUIA_Window_ID, (ULONG)"winny",
			MUIA_Window_Activate, TRUE,
			MUIA_Window_Height, 100,
			MUIA_Window_Width, 100,
			MUIA_Window_CloseGadget, TRUE,
			MUIA_Window_RootObject, MUI_NewObject(MUIC_Group,
				MUIA_Group_Horiz, FALSE,
				MUIA_Group_Child, MUI_NewObject(MUIC_Group,
					MUIA_Group_Horiz, TRUE,
					MUIA_Group_Child, MUI_NewObject(MUIC_	
				TAG_END),
				MUIA_Group_Child, MUI_NewObject(MUIC_Group,
					MUIA_Group_Horiz, TRUE,
				TAG_END),
				MUIA_Group_Child, MUI_NewObject(MUIC_Group,
					MUIA_Group_Horiz, TRUE,
				TAG_END),
			TAG_END),
		TAG_END)),
	TAG_END);